name: bi_t2_cardenas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.10
  - pip
  - jupyter
  - nbformat
  - ipykernel
  # - jupyterlab            # opcional
  - pip:
      - numpy==2.3.4
      - pandas==2.3.3
      - matplotlib==3.10.7
      - seaborn==0.13.2
      - scikit-learn==1.7.2
      - nbformat==5.10.4
      - ipykernel==7.1.0
      - jupyter==1.1.1

